export const STATUS_CHANGE = "STATUS_CHANGE";
export const TOGGLE_ENABLE_LOCATION_MODAL_VISIBLE = "TOGGLE_ENABLE_LOCATION_MODAL_VISIBLE";
export const SET_LOCATION = "SET_LOCATION";
export const SET_CURRENT_USER_MAP_SESSION_ID = "SET_CURRENT_USER_MAP_SESSION_ID";